#![cfg(any(
    feature = "draft15",
    feature = "draft16",
    feature = "draft17",
    feature = "draft18",
    feature = "draft19",
    feature = "draft20",
))]

//! A FETCH carries the parameters the caller gave it, as every other request
//! this endpoint makes does.
//!
//! Draft-15 Section 9.2.1 and draft-19 Section 10.2 define what a request's
//! parameters are and what may go in them, and every request message on these
//! six drafts draws a Parameters field. That is the whole of the rule this file
//! holds: the field is the caller's, and a FETCH is a request. It survives
//! draft-20 rebuilding the message around it.
//!
//! What a fetch cannot otherwise attach is the point. Draft-14's FETCH carries
//! a Subscriber Priority field of its own; drafts 15 and up have no such field
//! and put the priority in the parameters, where draft-17 Section 9.3.5 says it
//! "MAY appear in a SUBSCRIBE, FETCH, REQUEST_UPDATE (for a subscription or
//! FETCH), or PUBLISH_OK message". A fetch that sent an empty list here would
//! have no way to say what priority it wanted — not because no field carries
//! it, but because the field these drafts use is a parameter, and the
//! parameters are the caller's. An authorization token, which Section 9.3.2
//! puts in the same list, is the other thing such a fetch could not carry.
//!
//! # Why the range starts at 15
//!
//! Drafts 12, 13 and 14 have gates of their own, in
//! `a_fetch_carries_the_parameters_it_was_given_on_the_earlier_drafts.rs`,
//! because they need their own call shape: on those three the FETCH message
//! draws a Subscriber Priority and a Group Order field of its own, and
//! draft-15 deletes both fields and moves them into the parameters.
//!
//! # Both kinds of FETCH
//!
//! A Joining Fetch is the same message under a different Fetch Type, with one
//! Parameters field and the same registered parameters to put in it. It is
//! built by a call of its own on every draft that has one, so a change that
//! reached only the standalone call would leave the joining one sending an
//! empty list. That is why the third gate on each draft is the joining one.
//!
//! # Where draft-20 parts company
//!
//! It has one kind of FETCH. Section 10.13 deleted the Fetch Type field, the
//! Standalone and Joining structures and the Fetch Type registry, so there is
//! no `joining_fetch` to gate; the range moved into a `LOCATION_FILTER`
//! parameter and the call takes three arguments where the others take seven.
//!
//! Its gates are written out below the macro rather than generated by it. The
//! claim is the same and the first two gates are the same two assertions, but
//! the third has a different target: `fetch_range`, the second entry point that
//! builds a FETCH, which is where a caller's parameters can now be lost or
//! misordered. Filing draft-20 under a range that stops at 19 would have said
//! nothing about either.
//!
//! # Ablations, measured
//!
//! One cut was made, run against the two crates a change to
//! `moqtap-client` can reach, and reverted. There is one claim here
//! and one way to break it, so there is one cut; the second gate is
//! the control that keeps the first from being satisfied by a field
//! that is always full.
//!
//! ## And one more when the claim reached the other kind of FETCH
//!
//! The joining call has a builder of its own on each draft, so emptying the
//! standalone one leaves the joining gate green and the other way round. The
//! cut recorded on the third gate is the joining builder's.

#![allow(clippy::items_after_test_module)]

use moqtap_codec::types::TrackNamespace;
use moqtap_codec::varint::VarInt;

/// The namespace every fetch here is for.
fn namespace() -> TrackNamespace {
    TrackNamespace(vec![b"conformance".to_vec()])
}

fn v(n: u64) -> VarInt {
    VarInt::from_u64(n).unwrap()
}

/// One draft's gate.
macro_rules! fetch_parameter_gates {
    ($draft:ident, $feat:literal, $setup:tt) => {
        #[cfg(feature = $feat)]
        mod $draft {
            use moqtap_client::$draft::endpoint::Endpoint;
            use moqtap_client::$draft::session::request_id::Role;
            use moqtap_client::$draft::session::state::SessionState;
            use moqtap_codec::kvp::{KeyValuePair, KvpValue};
            #[allow(unused_imports)]
            use moqtap_codec::types::*;
            use moqtap_codec::$draft::message::*;

            /// A client with its session established and a budget to spend.
            fn active() -> Endpoint {
                let mut ep = Endpoint::new(Role::Client);
                ep.connect().expect("a client may open");
                crate::setup_for!($setup, ep);
                assert_eq!(
                    ep.session_state(),
                    SessionState::Active,
                    "the gate needs a running session"
                );
                ep
            }

            /// The parameter the caller attaches, chosen so that an empty
            /// list cannot be mistaken for it.
            ///
            /// It is SUBSCRIBER PRIORITY (0x20), which is the parameter that
            /// makes this claim load-bearing. Draft-14's FETCH carries a
            /// Subscriber Priority field of its own; drafts 15 and up drop the
            /// field and make it a parameter, and draft-17 Section 9.3.5 says
            /// it "MAY appear in a SUBSCRIBE, FETCH, REQUEST_UPDATE (for a
            /// subscription or FETCH), or PUBLISH_OK message". A fetch sending
            /// an empty parameter list on these five drafts could not carry a
            /// priority at all.
            ///
            /// Three things the codec enforces had to line up for this to be a
            /// usable choice, and each would have failed the gate for its own
            /// reason: the key must be one the draft registers, its value's
            /// encoding follows the key's parity, and drafts 17 through 20
            /// check that the parameter is in scope for the message carrying
            /// it.
            fn token() -> KeyValuePair {
                KeyValuePair { key: crate::v(0x20), value: KvpValue::Varint(crate::v(42)) }
            }

            /// The parameters a fetch is given reach the peer.
            ///
            /// # What it catches
            ///
            /// Sending an empty parameter list whatever the caller passed:
            ///
            /// ```text
            /// assertion `left == right` failed: the parameter the caller attached
            /// must reach the peer, not the empty list a call that ignores its
            /// argument sends left: 0 right: 1 failures:
            /// draft15::the_parameters_a_fetch_is_given_reach_the_peer
            /// ```
            ///
            /// It reddens five, this gate on every draft in the range and nothing
            /// else.
            #[test]
            fn the_parameters_a_fetch_is_given_reach_the_peer() {
                let mut ep = active();
                let (_, msg) = ep
                    .fetch(
                        crate::namespace(),
                        b"alpha".to_vec(),
                        crate::v(1),
                        crate::v(0),
                        crate::v(2),
                        crate::v(0),
                        vec![token()],
                    )
                    .expect("this endpoint may fetch with parameters");

                let mut buf = Vec::new();
                msg.encode(&mut buf).expect("the fetch encodes");
                let mut cursor = &buf[..];
                let ControlMessage::Fetch(back) =
                    ControlMessage::decode(&mut cursor).expect("the fetch decodes")
                else {
                    panic!("what was encoded was a FETCH");
                };
                assert_eq!(
                    back.parameters.len(),
                    1,
                    "the parameter the caller attached must reach the peer, not the empty \
                     list a call that ignores its argument sends"
                );
                assert_eq!(
                    back.parameters[0].key.into_inner(),
                    0x20,
                    "and it must be the one the caller passed"
                );
            }

            /// A fetch with nothing attached still carries nothing.
            ///
            /// The other half, and the reason it is here: a change that made
            /// the field always non-empty would pass the gate above.
            ///
            /// # What it catches
            ///
            /// Nothing the cut reaches, and that is what it is for. The one
            /// cut sends an empty list whatever it is given, which is what
            /// this gate asserts, so the cut leaves it green. It is the
            /// control for the gate above: without it, a change that filled
            /// the field with something of its own would pass the only other
            /// assertion in this file.
            #[test]
            fn a_fetch_given_no_parameters_carries_none() {
                let mut ep = active();
                let (_, msg) = ep
                    .fetch(
                        crate::namespace(),
                        b"alpha".to_vec(),
                        crate::v(1),
                        crate::v(0),
                        crate::v(2),
                        crate::v(0),
                        Vec::new(),
                    )
                    .expect("this endpoint may fetch without parameters");
                let ControlMessage::Fetch(built) = msg else {
                    panic!("what was built was a FETCH");
                };
                assert!(
                    built.parameters.is_empty(),
                    "an empty list is still what an empty list means"
                );
            }

            /// The other kind of FETCH carries them too.
            ///
            /// A Joining Fetch is a FETCH under a different Fetch Type: one
            /// Parameters field, the same registered parameters to put in it,
            /// and nothing about naming the range through a subscription
            /// rather than outright that changes what may be attached.
            ///
            /// The Request ID it joins names no subscription here, and the
            /// call does not mind: draft-15 Section 9.16.2 leaves that to the
            /// publisher, which "MUST return a REQUEST_ERROR with error code
            /// INVALID_JOINING_REQUEST_ID". What is being watched is the
            /// parameter list, and a fetch that never leaves the endpoint
            /// would not need one.
            ///
            /// # What it catches
            ///
            /// A joining fetch that sends an empty list whatever the caller
            /// passed:
            ///
            /// ```text
            /// assertion `left == right` failed: a Joining Fetch is a FETCH,
            /// and the parameter the caller attached must reach the peer
            ///   left: 0
            ///  right: 1
            /// ```
            ///
            /// It reddens one, this gate on the draft the cut was made in,
            /// because each draft builds its own message.
            #[test]
            fn the_parameters_a_joining_fetch_is_given_reach_the_peer() {
                let mut ep = active();
                let (_, msg) = ep
                    .joining_fetch(crate::v(0), crate::v(2), vec![token()])
                    .expect("this endpoint may join a subscription with parameters");

                let mut buf = Vec::new();
                msg.encode(&mut buf).expect("the fetch encodes");
                let mut cursor = &buf[..];
                let ControlMessage::Fetch(back) =
                    ControlMessage::decode(&mut cursor).expect("the fetch decodes")
                else {
                    panic!("what was encoded was a FETCH");
                };
                assert_eq!(
                    back.parameters.len(),
                    1,
                    "a Joining Fetch is a FETCH, and the parameter the caller attached must \
                     reach the peer"
                );
                assert_eq!(
                    back.parameters[0].key.into_inner(),
                    0x20,
                    "and it must be the one the caller passed"
                );
            }
        }
    };
}

/// SETUP, in the two shapes these five drafts take.
#[macro_export]
macro_rules! setup_for {
    (alpn, $ep:expr) => {{
        let _ = $ep.send_client_setup(vec![]).expect("CLIENT_SETUP");
        $ep.receive_server_setup(&ServerSetup {
            parameters: vec![KeyValuePair {
                key: $crate::v(0x02),
                value: KvpValue::Varint($crate::v(100)),
            }],
        })
        .expect("SERVER_SETUP");
        let _ = $ep.send_max_request_id($crate::v(100)).expect("MAX_REQUEST_ID");
    }};
    (options, $ep:expr) => {{
        let _ = $ep.send_setup(vec![]).expect("SETUP");
        $ep.receive_setup(&Setup { options: vec![] }).expect("SETUP");
    }};
}

fetch_parameter_gates!(draft15, "draft15", alpn);
fetch_parameter_gates!(draft16, "draft16", alpn);
fetch_parameter_gates!(draft17, "draft17", options);
fetch_parameter_gates!(draft18, "draft18", options);
fetch_parameter_gates!(draft19, "draft19", options);

/// Draft-20's three gates, which cannot share the macro above.
///
/// Section 10.13 rebuilt FETCH: the Fetch Type field, the Standalone and
/// Joining structures and the Fetch Type registry are gone, the namespace and
/// name are inline fields, and the range travels in a `LOCATION_FILTER`
/// parameter. So `fetch` takes three arguments where its predecessors took
/// seven, and there is no `joining_fetch` to call at all.
///
/// The claim is the same claim — a FETCH carries the parameters the caller gave
/// it — and it is asserted the same three ways. Only the third gate changes
/// target, and it changes to the thing that now occupies the same position: a
/// second entry point that builds the message itself and could therefore lose
/// the caller's list on its own. On drafts 15 through 19 that was
/// `joining_fetch`; here it is `fetch_range`.
///
/// # `fetch_range` fails in a way no earlier fetch could
///
/// `joining_fetch` could only ever drop the list. `fetch_range` *inserts* into
/// it — the range is a parameter now, so the convenience method builds a
/// `LOCATION_FILTER` (0x21) and puts it in at the position ascending Parameter
/// Type order requires. It cannot overwrite an entry, because `Vec::insert`
/// shifts rather than replaces; what it can get wrong is the position, and
/// Section 10.2 makes the order a wire rule rather than a convention — the
/// encoder refuses a descending pair rather than emitting one. So the assertion
/// is that both parameters arrive *and* that they arrive in order, and the
/// second half is the half that is new here.
///
/// # Ablations, measured
///
/// Two cuts, one per entry point, each run and reverted.
///
/// `fetch_range` stopped inserting its filter, keeping the `range.parameter()`
/// call so the cut is the insertion and not the construction:
///
/// ```text
/// assertion `left == right` failed: the filter is added to the caller's list,
/// not put in place of it; got [34]
/// ```
///
/// 17 passed, 1 failed — only the third gate, which is what says the third gate
/// is not a restatement of the first.
///
/// Then `fetch` itself sending an empty list whatever it was given, which is
/// the cut the five drafts above record:
///
/// ```text
/// assertion `left == right` failed: the parameter the caller attached must
/// reach the peer
/// ```
///
/// 16 passed, 2 failed — the first and third gates, because `fetch_range`
/// builds its message through `fetch`. The second gate stays green under both
/// cuts, which is the control working: it asserts an empty list stays empty,
/// and a call that empties everything satisfies it.
#[cfg(feature = "draft20")]
mod draft20 {
    use moqtap_client::draft20::endpoint::Endpoint;
    use moqtap_client::draft20::fill::LocationFilter;
    use moqtap_client::draft20::session::request_id::Role;
    use moqtap_client::draft20::session::state::SessionState;
    use moqtap_codec::draft20::message::*;
    use moqtap_codec::kvp::{KeyValuePair, KvpValue};
    #[allow(unused_imports)]
    use moqtap_codec::types::*;

    fn active() -> Endpoint {
        let mut ep = Endpoint::new(Role::Client);
        ep.connect().expect("a client may open");
        let _ = ep.send_setup(vec![]).expect("SETUP");
        ep.receive_setup(&Setup { options: vec![] }).expect("SETUP");
        assert_eq!(ep.session_state(), SessionState::Active, "the gate needs a running session");
        ep
    }

    /// The parameter the caller attaches.
    ///
    /// GROUP_ORDER (0x22) rather than the SUBSCRIBER PRIORITY (0x20) the five
    /// drafts above use, and the choice is what makes the third gate mean
    /// something: 0x22 sorts *above* draft-20's LOCATION_FILTER (0x21), so
    /// `fetch_range` has to search for the insertion point and put its filter
    /// in front of this one. A key below 0x21 is appended after it and never
    /// exercises the search at all.
    ///
    /// Two of the codec's rules narrowed this to one usable key, and the two
    /// that were tried first each failed the gate for its own reason. The value
    /// is `2` because Section 12.5 holds GROUP_ORDER to `{1, 2}`.
    ///
    /// The obvious pick was one of the Range Filters, since 0x25 through 0x29
    /// all sort above the filter and all admit a FETCH. They are
    /// length-prefixed: draft-20 puts them in the same value class as
    /// AUTHORIZATION_TOKEN regardless of key parity, so a `Varint` there
    /// decodes as `ControlMessageLengthMismatch` rather than as a wrong value.
    /// That leaves 0x0A, 0x20, 0x22 and 0x35 as the plainly varint-valued
    /// parameters a FETCH may carry, and 0x22 is the only one of the four above
    /// 0x21.
    fn token() -> KeyValuePair {
        KeyValuePair { key: crate::v(GROUP_ORDER_PARAMETER), value: KvpValue::Varint(crate::v(2)) }
    }

    /// GROUP_ORDER as a parameter type, draft-20 Section 10.2.8.
    const GROUP_ORDER_PARAMETER: u64 = 0x22;

    fn decoded(msg: ControlMessage) -> Fetch {
        let mut buf = Vec::new();
        msg.encode(&mut buf).expect("the fetch encodes");
        let mut cursor = &buf[..];
        let ControlMessage::Fetch(back) =
            ControlMessage::decode(&mut cursor).expect("the fetch decodes")
        else {
            panic!("what was encoded was a FETCH");
        };
        back
    }

    /// The parameters a fetch is given reach the peer.
    #[test]
    fn the_parameters_a_fetch_is_given_reach_the_peer() {
        let mut ep = active();
        let (_, msg) = ep
            .fetch(crate::namespace(), b"alpha".to_vec(), vec![token()])
            .expect("this endpoint may fetch with parameters");
        let back = decoded(msg);
        assert_eq!(
            back.parameters.len(),
            1,
            "the parameter the caller attached must reach the peer"
        );
        assert_eq!(
            back.parameters[0].key.into_inner(),
            GROUP_ORDER_PARAMETER,
            "and it must be the one the caller passed"
        );
    }

    /// A fetch with nothing attached still carries nothing.
    ///
    /// The control, as above: a change that made the field always non-empty
    /// would pass the gate before it.
    #[test]
    fn a_fetch_given_no_parameters_carries_none() {
        let mut ep = active();
        let (_, msg) = ep
            .fetch(crate::namespace(), b"alpha".to_vec(), Vec::new())
            .expect("this endpoint may fetch without parameters");
        let ControlMessage::Fetch(built) = msg else {
            panic!("what was built was a FETCH");
        };
        assert!(built.parameters.is_empty(), "an empty list is still what an empty list means");
    }

    /// The range convenience keeps what the caller already put in the list.
    ///
    /// `fetch_range` is the entry point that has to insert, so it is the one
    /// that can displace. Both parameters must arrive, and in ascending
    /// Parameter Type order, because Section 10.2 makes that order a wire rule
    /// and the codec's encoder refuses a descending pair rather than emitting
    /// one — which is why an encode-and-decode round trip is the assertion
    /// rather than a look at the built message.
    #[test]
    fn a_ranged_fetch_keeps_the_callers_parameters_beside_its_filter() {
        let mut ep = active();
        let range = LocationFilter::range(0, 0, 2).expect("a range across three groups");
        let (_, msg) = ep
            .fetch_range(crate::namespace(), b"alpha".to_vec(), &range, vec![token()])
            .expect("this endpoint may fetch a range with parameters");
        let back = decoded(msg);

        let keys: Vec<u64> = back.parameters.iter().map(|p| p.key.into_inner()).collect();
        assert_eq!(
            keys.len(),
            2,
            "the filter is added to the caller's list, not put in place of it; got {keys:?}"
        );
        assert!(
            keys.contains(&GROUP_ORDER_PARAMETER),
            "the caller's own parameter must survive the insertion; got {keys:?}"
        );
        let mut sorted = keys.clone();
        sorted.sort_unstable();
        assert_eq!(keys, sorted, "and the two must be in ascending Parameter Type order");
    }
}
